name: Build datagen
on:
  workflow_dispatch:
  push:
    tags:
      - 20[0-9][0-9]-[0-1][0-9]-[0-3][0-9]*
jobs:
  build:
    uses: ./.github/workflows/dockerfiles.yaml
    with:
      image: ingkle/datagen
      path: ./
      build_runner: self-hosted
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
