name: Pyright

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - master

permissions:
  contents: read

jobs:
  pyright:
    permissions:
      contents: read
    name: pyright/ci
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v3
      - name: Install librdkafka-dev
        run: sudo apt-get update && sudo apt-get install -y librdkafka-dev
      - name: Install dependencies
        run: uv sync
      - run: python -m venv venv
      - run: |
          source ./venv/bin/activate
      - uses: jakebailey/pyright-action@v2
        with:
          working-directory: "."
