name: Pyright

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  pyright:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v3
      - name: Install librdkafka-dev
        run: sudo apt-get update && sudo apt-get install -y librdkafka-dev
      - name: Install dependencies
        run: uv sync
      - run: python -m venv venv
      - run: |
          source ./venv/bin/activate
      - uses: jakebailey/pyright-action@v2
        with:
          working-directory: "./src"
